name: abstract_lerp
description: A package that gives you interpolation on Fields from abstract_dart
version: 1.0.0
homepage: https://www.github.com/modulovalue/abstract_lerp
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>
issue_tracker: https://github.com/modulovalue/abstract_lerp/issues

environment:
  sdk: '>=2.4.4 <3.0.0'

dependencies:
  abstract_dart: ^1.0.0

dev_dependencies:
  extra_pedantic: ^1.1.1+3
  test: ^1.5.0
  test_coverage: ^0.2.0